//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullanici
    {
        public int KullaniciID { get; set; }
        public string KullaniciAd { get; set; }
        public string KullaniciSoyad { get; set; }
        public string KullaniciTel { get; set; }
        public string KullaniciMail { get; set; }
        public Nullable<int> KullaniciDYili { get; set; }
        public string KullaniciTC { get; set; }
        public string KullaniciSifre { get; set; }
        public Nullable<int> RolID { get; set; }
    
        public virtual tblRol tblRol { get; set; }
    }
}
