//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOgrenci
    {
        public int ogrenciID { get; set; }
        public string OgrenciAd { get; set; }
        public string OgrenciSoyad { get; set; }
        public string OgrenciTC { get; set; }
        public string OgrenciSifre { get; set; }
        public string OgrenciTelefon { get; set; }
        public string OgrenciCinsiyet { get; set; }
        public Nullable<int> OgrenciOdaID { get; set; }
        public string OgrenciMail { get; set; }
        public Nullable<int> OgrenciKalanBorc { get; set; }
        public string OgrenciVeliTel { get; set; }
        public string OgrenciVeliAd { get; set; }
        public string OgrenciVeliSoyad { get; set; }
        public Nullable<int> OgrenciDYılı { get; set; }
    
        public virtual tblOda tblOda { get; set; }
    }
}
