//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOda()
        {
            this.tblOgrenci = new HashSet<tblOgrenci>();
        }
    
        public int OdaID { get; set; }
        public Nullable<int> OdaKapasite { get; set; }
        public Nullable<bool> OdaAktiflik { get; set; }
        public Nullable<int> OdaNo { get; set; }
        public Nullable<int> OdaMevcutKisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgrenci> tblOgrenci { get; set; }
    }
}
