//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonel
    {
        public int PersonelID { get; set; }
        public string PersonelAd { get; set; }
        public string PersonelSoyad { get; set; }
        public string PersonelTC { get; set; }
        public string PersonelSifre { get; set; }
        public string PersonelCinsiyet { get; set; }
        public Nullable<int> RolID { get; set; }
        public Nullable<int> PersonelMaas { get; set; }
        public string PersonelTelefon { get; set; }
        public string PersonelAdres { get; set; }
    }
}
